export type PortfolioCategory =
  | "bridal"
  | "wedding"
  | "editorial"
  | "event"
  | "natural";

export interface PortfolioImage {
  id: number;
  src: string;
  alt: string;
  altEn: string;
  category: PortfolioCategory;
  caption?: string;
  captionEn?: string;
  aspect: "portrait" | "landscape" | "square";
}

export const portfolioImages: PortfolioImage[] = [
  // Gökçe Çekimleri & Portreler
  {
    id: 1,
    src: "/images/gockecekim1.jpeg",
    alt: "Gökçe Dila Çağlayan - Set & Editöryal Çekim",
    altEn: "Gökçe Dila Çağlayan - Set & Editorial Shoot",
    category: "editorial",
    caption: "Gökçe Dila · Set Çekimi",
    captionEn: "Gökçe Dila · Set Shoot",
    aspect: "portrait",
  },
  {
    id: 2,
    src: "/images/gockecekim2.jpeg",
    alt: "Gökçe Dila Çağlayan - Sanatçı Portresi",
    altEn: "Gökçe Dila Çağlayan - Artist Portrait",
    category: "editorial",
    caption: "Gökçe Dila · Portre",
    captionEn: "Gökçe Dila · Portrait",
    aspect: "portrait",
  },
  {
    id: 3,
    src: "/images/gockecekim3.jpeg",
    alt: "Gökçe Dila Çağlayan - Stüdyo Çekimi",
    altEn: "Gökçe Dila Çağlayan - Studio Shoot",
    category: "editorial",
    caption: "Gökçe Dila · Stüdyo",
    captionEn: "Gökçe Dila · Studio",
    aspect: "portrait",
  },
  {
    id: 4,
    src: "/images/gokcecekim4.jpeg",
    alt: "Gökçe Dila Çağlayan - Backstage Çalışması",
    altEn: "Gökçe Dila Çağlayan - Backstage Work",
    category: "editorial",
    caption: "Backstage Anı",
    captionEn: "Backstage Moment",
    aspect: "portrait",
  },
  {
    id: 5,
    src: "/images/gockecekim5.jpeg",
    alt: "Gökçe Dila Çağlayan - Çekim Hazırlığı",
    altEn: "Gökçe Dila Çağlayan - Shoot Preparation",
    category: "editorial",
    caption: "Çekim Hazırlığı",
    captionEn: "Shoot Prep",
    aspect: "portrait",
  },
  {
    id: 6,
    src: "/images/gockecekim6.jpeg",
    alt: "Gökçe Dila Çağlayan - Kulis Anları",
    altEn: "Gökçe Dila Çağlayan - Backstage Moments",
    category: "editorial",
    caption: "Kulis Anları",
    captionEn: "Backstage Moments",
    aspect: "portrait",
  },
  // Gelin & Model Çekimleri
  {
    id: 7,
    src: "/images/bridal.jpeg",
    alt: "Gelin makyajı - lüks gelin görünümü İstanbul",
    altEn: "Bridal makeup - luxury bridal look Istanbul",
    category: "bridal",
    caption: "Lüks Gelin İmzası",
    captionEn: "Luxury Bridal Signature",
    aspect: "portrait",
  },
  {
    id: 8,
    src: "/images/bridal2.jpeg",
    alt: "Gelin makyajı - romantik ve soft glam görünüm",
    altEn: "Bridal makeup - romantic soft glam look",
    category: "bridal",
    caption: "Soft Glam Gelin",
    captionEn: "Soft Glam Bride",
    aspect: "portrait",
  },
  {
    id: 9,
    src: "/images/beyazmodel.jpeg",
    alt: "Gelin makyajı - soft glam düğün görünümü İstanbul",
    altEn: "Bridal makeup - soft glam wedding look Istanbul",
    category: "bridal",
    caption: "Couture Gelin",
    captionEn: "Couture Bridal",
    aspect: "portrait",
  },
  {
    id: 10,
    src: "/images/eyeliner.jpeg",
    alt: "Editöryal makyaj çekimi - grafik eyeliner görünümü",
    altEn: "Editorial makeup shoot - graphic eyeliner look",
    category: "editorial",
    caption: "Grafik Eyeliner",
    captionEn: "Graphic Eyeliner",
    aspect: "portrait",
  },
  {
    id: 11,
    src: "/images/asliyelpaze.jpeg",
    alt: "Gelin makyajı - klasik zarif görünüm",
    altEn: "Bridal makeup - classic elegant look",
    category: "bridal",
    caption: "Romantik Gelin",
    captionEn: "Romantic Bridal",
    aspect: "portrait",
  },
  {
    id: 12,
    src: "/images/asliyelpaze2.jpeg",
    alt: "Gelin makyajı - detay görünüm",
    altEn: "Bridal makeup - detail look",
    category: "bridal",
    caption: "Gelin Detay",
    captionEn: "Bridal Detail",
    aspect: "portrait",
  },
  {
    id: 13,
    src: "/images/asufte.jpeg",
    alt: "Moda editöryal çekim - avant garde makyaj",
    altEn: "Fashion editorial shoot - avant garde makeup",
    category: "editorial",
    caption: "Vogue Editöryal",
    captionEn: "Vogue Editorial",
    aspect: "portrait",
  },
  {
    id: 14,
    src: "/images/asufte2.jpeg",
    alt: "Özel davet makyajı - lüks gala stili",
    altEn: "Special party makeup - luxury gala style",
    category: "event",
    caption: "Gala Elegansı",
    captionEn: "Gala Elegance",
    aspect: "portrait",
  },
  {
    id: 15,
    src: "/images/cilek1.jpeg",
    alt: "Yaratıcı güzellik makyajı - renkli konsept",
    altEn: "Creative beauty makeup - colorful concept",
    category: "editorial",
    caption: "Sanatsal Konsept I",
    captionEn: "Artistic Concept I",
    aspect: "portrait",
  },
  {
    id: 16,
    src: "/images/cilek2.jpeg",
    alt: "Yaratıcı güzellik makyajı - renkli konsept II",
    altEn: "Creative beauty makeup - colorful concept II",
    category: "editorial",
    caption: "Sanatsal Konsept II",
    captionEn: "Artistic Concept II",
    aspect: "portrait",
  },
  {
    id: 17,
    src: "/images/dilay1.jpeg",
    alt: "Düğün makyajı - zarif gece görünümü",
    altEn: "Wedding makeup - elegant evening look",
    category: "wedding",
    caption: "Nispetiye Işıltısı I",
    captionEn: "Evening Radiance I",
    aspect: "portrait",
  },
  {
    id: 18,
    src: "/images/dilay2.jpeg",
    alt: "Düğün makyajı - zarif gece görünümü II",
    altEn: "Wedding makeup - elegant evening look II",
    category: "wedding",
    caption: "Nispetiye Işıltısı II",
    captionEn: "Evening Radiance II",
    aspect: "portrait",
  },
  {
    id: 19,
    src: "/images/kedi1.jpeg",
    alt: "Editöryal göz makyajı - smokey cat eye I",
    altEn: "Editorial eye makeup - smokey cat eye I",
    category: "editorial",
    caption: "Cat Eye Glam I",
    captionEn: "Cat Eye Glam I",
    aspect: "portrait",
  },
  {
    id: 20,
    src: "/images/kedi2.jpeg",
    alt: "Editöryal göz makyajı - smokey cat eye II",
    altEn: "Editorial eye makeup - smokey cat eye II",
    category: "editorial",
    caption: "Cat Eye Glam II",
    captionEn: "Cat Eye Glam II",
    aspect: "portrait",
  },
  {
    id: 21,
    src: "/images/merve1.jpeg",
    alt: "Özel gün makyajı - nişan daveti görünümü",
    altEn: "Special event makeup - engagement party look",
    category: "event",
    caption: "Zarif Nişan I",
    captionEn: "Elegant Engagement I",
    aspect: "portrait",
  },
  {
    id: 22,
    src: "/images/merve2.jpeg",
    alt: "Nedime ve nikah makyajı - şık görünüm",
    altEn: "Bridesmaid & registry makeup - chic look",
    category: "wedding",
    caption: "Nikah Şıklığı",
    captionEn: "Registry Chic",
    aspect: "portrait",
  },
  {
    id: 23,
    src: "/images/merve3.jpeg",
    alt: "Özel gün makyajı - nişan daveti görünümü II",
    altEn: "Special event makeup - engagement party look II",
    category: "event",
    caption: "Zarif Nişan II",
    captionEn: "Elegant Engagement II",
    aspect: "portrait",
  },
  {
    id: 24,
    src: "/images/naz.jpeg",
    alt: "Gelin makyajı - doğal ve ışıltılı stil I",
    altEn: "Bridal makeup - natural glowing style I",
    category: "bridal",
    caption: "Işıltılı Gelin I",
    captionEn: "Glowing Bride I",
    aspect: "portrait",
  },
  {
    id: 25,
    src: "/images/naz1.jpeg",
    alt: "Gelin makyajı - doğal ve ışıltılı stil II",
    altEn: "Bridal makeup - natural glowing style II",
    category: "bridal",
    caption: "Işıltılı Gelin II",
    captionEn: "Glowing Bride II",
    aspect: "portrait",
  },
  {
    id: 26,
    src: "/images/oyku1.jpeg",
    alt: "Doğal makyaj - minimal taze ten makyajı I",
    altEn: "Natural makeup - minimal fresh skin makeup I",
    category: "natural",
    caption: "Taze Ten I",
    captionEn: "Fresh Skin I",
    aspect: "portrait",
  },
  {
    id: 27,
    src: "/images/oyku2.jpeg",
    alt: "Doğal güzellik makyajı - nude dudak ve ışıltı",
    altEn: "Natural beauty makeup - nude lips and glow",
    category: "natural",
    caption: "Natürel Nude",
    captionEn: "Natural Nude",
    aspect: "portrait",
  },
  {
    id: 28,
    src: "/images/rengarenk1.jpeg",
    alt: "Kreatif makyaj - renkli editoryal tasarım I",
    altEn: "Creative makeup - colorful editorial design I",
    category: "editorial",
    caption: "Renk Harmonisi I",
    captionEn: "Color Harmony I",
    aspect: "portrait",
  },
  {
    id: 29,
    src: "/images/rengarenk2.jpeg",
    alt: "Kreatif makyaj - renkli editoryal tasarım II",
    altEn: "Creative makeup - colorful editorial design II",
    category: "editorial",
    caption: "Renk Harmonisi II",
    captionEn: "Color Harmony II",
    aspect: "portrait",
  },
  {
    id: 30,
    src: "/images/siyah1.jpeg",
    alt: "Gece makyajı - dramatik smokey görünüm I",
    altEn: "Evening makeup - dramatic smokey look I",
    category: "event",
    caption: "Dramatik Gece I",
    captionEn: "Dramatic Evening I",
    aspect: "portrait",
  },
  {
    id: 31,
    src: "/images/siyah2.jpeg",
    alt: "Gece makyajı - dramatik smokey görünüm II",
    altEn: "Evening makeup - dramatic smokey look II",
    category: "event",
    caption: "Dramatik Gece II",
    captionEn: "Dramatic Evening II",
    aspect: "portrait",
  },
  {
    id: 32,
    src: "/images/siyah3.jpeg",
    alt: "Gece makyajı - dumanlı görünüm III",
    altEn: "Evening makeup - dumanlı look III",
    category: "event",
    caption: "Dramatik Gece III",
    captionEn: "Dramatic Evening III",
    aspect: "portrait",
  },
  {
    id: 33,
    src: "/images/yesil1.jpeg",
    alt: "Editöryal renkli tonlar - moda makyajı I",
    altEn: "Editorial colorful tones - fashion makeup I",
    category: "editorial",
    caption: "Zümrüt Dokunuş I",
    captionEn: "Emerald Touch I",
    aspect: "portrait",
  },
  {
    id: 34,
    src: "/images/yesil2.jpeg",
    alt: "Editöryal renkli tonlar - moda makyajı II",
    altEn: "Editorial colorful tones - fashion makeup II",
    category: "editorial",
    caption: "Zümrüt Dokunuş II",
    captionEn: "Emerald Touch II",
    aspect: "portrait",
  },
  {
    id: 35,
    src: "/images/kis1.jpeg",
    alt: "Kış gelin makyajı - soft ve sıcak tonlar I",
    altEn: "Winter bridal makeup - soft warm tones I",
    category: "bridal",
    caption: "Kış Gelini I",
    captionEn: "Winter Bride I",
    aspect: "portrait",
  },
  {
    id: 36,
    src: "/images/kis2.jpeg",
    alt: "Kış gelin makyajı - soft ve sıcak tonlar II",
    altEn: "Winter bridal makeup - soft warm tones II",
    category: "bridal",
    caption: "Kış Gelini II",
    captionEn: "Winter Bride II",
    aspect: "portrait",
  },
  {
    id: 37,
    src: "/images/kis3.jpeg",
    alt: "Kış gelin makyajı - soft ve sıcak tonlar III",
    altEn: "Winter bridal makeup - soft warm tones III",
    category: "bridal",
    caption: "Kış Gelini III",
    captionEn: "Winter Bride III",
    aspect: "portrait",
  },
  {
    id: 38,
    src: "/images/kis4.jpeg",
    alt: "Kış gelin makyajı - detay IV",
    altEn: "Winter bridal makeup - detail IV",
    category: "bridal",
    caption: "Kış Gelini IV",
    captionEn: "Winter Bride IV",
    aspect: "portrait",
  },
  {
    id: 39,
    src: "/images/kis5.jpeg",
    alt: "Kış gelin makyajı - detay V",
    altEn: "Winter bridal makeup - detail V",
    category: "bridal",
    caption: "Kış Gelini V",
    captionEn: "Winter Bride V",
    aspect: "portrait",
  },
  {
    id: 40,
    src: "/images/model.jpeg",
    alt: "Doğal güzellik çekimi",
    altEn: "Natural beauty shoot",
    category: "natural",
    caption: "Natürel Model",
    captionEn: "Natural Model",
    aspect: "portrait",
  }
];
